In [19]:
import numpy as np
import pandas as pd

marvel = pd.read_csv("/kaggle/input/datasets/fivethirtyeight/fivethirtyeight-comic-characters-dataset/marvel-wikia-data.csv")
marvel.head()

,page_id,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,Year
0,1678,Spider-Man (Peter Parker),\/Spider-Man_(Peter_Parker),Secret Identity,Good Characters,Hazel Eyes,Brown Hair,Male Characters,NaN,Living Characters,4043.0,Aug-62,1962.0
1,7139,Captain America (Steven Rogers),\/Captain_America_(Steven_Rogers),Public Identity,Good Characters,Blue Eyes,White Hair,Male Characters,NaN,Living Characters,3360.0,Mar-41,1941.0
2,64786,"Wolverine (James \""Logan\"" Howlett)",\/Wolverine_(James_%22Logan%22_Howlett),Public Identity,Neutral Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,3061.0,Oct-74,1974.0
3,1868,"Iron Man (Anthony \""Tony\"" Stark)",\/Iron_Man_(Anthony_%22Tony%22_Stark),Public Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,2961.0,Mar-63,1963.0
4,2460,Thor (Thor Odinson),\/Thor_(Thor_Odinson),No Dual Identity,Good Characters,Blue Eyes,Blond Hair,Male Characters,NaN,Living Characters,2258.0,Nov-50,1950.0

In [20]:
marvel.describe()

             page_id   APPEARANCES          Year
count   16376.000000  15280.000000  15561.000000
mean   300232.082377     17.033377   1984.951803
std    253460.403399     96.372959     19.663571
min      1025.000000      1.000000   1939.000000
25%     28309.500000      1.000000   1974.000000
50%    282578.000000      3.000000   1990.000000
75%    509077.000000      8.000000   2000.000000
max    755278.000000   4043.000000   2013.000000

In [21]:
marvel.isnull()

,page_id,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,Year
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16371,False,False,False,False,False,False,False,False,True,False,True,True,True
16372,False,False,False,False,False,False,False,False,True,False,True,True,True
16373,False,False,False,False,False,False,False,False,True,False,True,True,True
16374,False,False,False,False,False,True,True,False,True,False,True,True,True
16375,False,False,False,True,False,True,True,True,True,False,True,True,True

In [22]:
marvel.shape

(16376, 13)

In [27]:
dc = pd.read_csv("/kaggle/input/datasets/fivethirtyeight/fivethirtyeight-comic-characters-dataset/dc-wikia-data.csv")

In [28]:
dc.head()

,page_id,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,YEAR
0,1422,Batman (Bruce Wayne),\/wiki\/Batman_(Bruce_Wayne),Secret Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,3093.0,"1939, May",1939.0
1,23387,Superman (Clark Kent),\/wiki\/Superman_(Clark_Kent),Secret Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,2496.0,"1986, October",1986.0
2,1458,Green Lantern (Hal Jordan),\/wiki\/Green_Lantern_(Hal_Jordan),Secret Identity,Good Characters,Brown Eyes,Brown Hair,Male Characters,NaN,Living Characters,1565.0,"1959, October",1959.0
3,1659,James Gordon (New Earth),\/wiki\/James_Gordon_(New_Earth),Public Identity,Good Characters,Brown Eyes,White Hair,Male Characters,NaN,Living Characters,1316.0,"1987, February",1987.0
4,1576,Richard Grayson (New Earth),\/wiki\/Richard_Grayson_(New_Earth),Secret Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,1237.0,"1940, April",1940.0

In [29]:
dc.shape

(6896, 13)

In [35]:
for d in (dc , marvel):
    d.columns = d.columns.str.upper()

dc['PUBLISHER'] , marvel['PUBLISHER'] ='DC','Marvel'

df = pd.concat([dc , marvel],ignore_index = True)
print(df.shape)

df = df[df['ALIGN'].isin(['Good Characters' , 'Bad Characters'])]
print(df.shape)

print(df['ALIGN'].value_counts().to_dict())

(23272, 14)
(17083, 14)
{'Bad Characters': 9615, 'Good Characters': 7468}

In [37]:
def tidy(col , keep):
    s = df[col].fillna('Unknown').str.replace('Characters | Eyes | Hair | Identity', ' ', regex = True)
    return s.where(s.isin(s.value_counts().index[:keep]),'Other')

x = pd.get_dummies(pd.DataFrame({
    'publisher' : df['PUBLISHER'], 'sex' : tidy('SEX',2), 'identity' : tidy('ID',3),
    'alive': tidy('ALIVE',2), 'eye': tidy('EYE',5), 'hair': tidy('HAIR',5)
}), dtype =float)

x['appearances'] = np.log1p(df['APPEARANCES'].fillna(1))
x['year'] = df['YEAR'].fillna(df['YEAR'].median())
y = (df['ALIGN'] == 'Bad Characters').astype(int)

print(x.shape,round(y.mean(),3))
print(list(x.columns[:6]))

(17083, 26) 0.563
['publisher_DC', 'publisher_Marvel', 'sex_Female', 'sex_Male', 'sex_Other', 'identity_Other']

In [40]:
def tidy(col, keep):
    s = df[col].fillna('Unknown').str.replace(' Characters| Eyes| Hair| Identity', '',
    regex=True)
    return s.where(s.isin(s.value_counts().index[:keep]), 'Other')
x = pd.get_dummies(pd.DataFrame({
        'publisher': df['PUBLISHER'], 'sex': tidy('SEX', 2), 'identity': tidy('ID', 3),
        'alive': tidy('ALIVE', 2), 'eye': tidy('EYE', 5), 'hair': tidy('HAIR', 5)}), dtype=float)
x['appearances'] = np.log1p(df['APPEARANCES'].fillna(1))
x['year'] = df['YEAR'].fillna(df['YEAR'].median())
y = (df['ALIGN'] == 'Bad Characters').astype(int) # 1 = villain
print(x.shape, round(y.mean(), 3)) # (17083, 26) 0.563
print(list(x.columns[:6]))

(17083, 26) 0.563
['publisher_DC', 'publisher_Marvel', 'sex_Female', 'sex_Male', 'sex_Other', 'identity_Other']

In [43]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

x_train,x_test, y_train, y_test  = train_test_split(x,y,test_size = 0.2, random_state = 42)
x_train,x_val, y_train, y_val  = train_test_split(x,y,test_size = 0.2, random_state = 42)

test_names = df.loc[x_test.index , 'NAME'].values
print(test_names)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_val, x_test =  scaler.transform(x_val), scaler.transform(x_test)
y_train, y_val , y_test = [v.values.reshape(-1,1) for v in (y_train,y_val , y_test)]

print(x_train.shape, x_val.shape , x_test.shape)

['Bennet du Paris (Earth-616)' 'Torkon II (Earth-616)'
 'Tia Senyaka (Earth-616)' ... 'Eric Hertz (Earth-616)'
 'Elsie Gertz (Earth-616)' 'Jocasta (Earth-616)']
(13666, 26) (3417, 26) (3417, 26)

Neural Networks by Hand

In [51]:
rng = np.random.default_rng(42)
w1 = rng.normal(0,0.5,(26,8)); b1 = np.zeros(8)
w2 = rng.normal(0,0.5,(8,1)); b2 = np.zeros(1)
sigmoid = lambda z: 1/(1 + np.exp(-z))

#forward pass:

z1 = x_train @ w1 + b1
a1 = np.maximum(0,z1)
p = sigmoid(a1 @ w2 + b2)
print(p)
#loss

loss = np.mean((p - y_train) ** 2)

[[0.07303014]
 [0.15500565]
 [0.03657278]
 ...
 [0.31428449]
 [0.44966095]
 [0.08296797]]

In [57]:
#backward pass

dz2 = 2 * (p - y_train) * p * (1 - p) / len(y_train) 
dW2 = a1.T @ dz2; db2 = dz2.sum(axis=0)
dz1 = (dz2 @ w2.T) * (z1 > 0) 
dW1 = x_train.T @ dz1; db1 = dz1.sum(axis=0)

# update: gradient descent
lr = 0.5
w1 -= lr * dW1; b1 -= lr * db1
w2 -= lr * dW2; b2 -= lr * db2

By Tensor Flow

In [62]:
import tensorflow as tf

tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape =(26,)),
    tf.keras.layers.Dense(8,activation ="relu"),
    tf.keras.layers.Dense(1, activation ="sigmoid")
])
model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01),
             loss ="mse",metrics= ["accuracy"])
model.fit(x_train, y_train, validation_data=(x_val, y_val),
        epochs=100, batch_size=len(x_train))
loss, acc = model.evaluate(x_test, y_test)

print(loss, acc)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 983ms/step - accuracy: 0.5275 - loss: 0.2993 - val_accuracy: 0.5186 - val_loss: 0.2976
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5398 - loss: 0.2890 - val_accuracy: 0.5397 - val_loss: 0.2873
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5669 - loss: 0.2791 - val_accuracy: 0.5414 - val_loss: 0.2777
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5713 - loss: 0.2698 - val_accuracy: 0.5464 - val_loss: 0.2688
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5760 - loss: 0.2613 - val_accuracy: 0.5511 - val_loss: 0.2607
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5814 - loss: 0.2537 - val_accuracy: 0.5625 - val_loss: 0.2536
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5912 - loss: 0.2470 - val_accuracy: 0.5669 - val_loss: 0.2474
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5964 - loss: 0.2412 - val_accuracy: 0.5701 - val_loss: 0.2421
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6018 - loss: 0.2363 - val_accuracy: 0.5847 - val_loss: 0.2376
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6098 - loss: 0.2321 - val_accuracy: 0.5985 - val_loss: 0.2339
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6198 - loss: 0.2286 - val_accuracy: 0.6128 - val_loss: 0.2308
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6319 - loss: 0.2258 - val_accuracy: 0.6228 - val_loss: 0.2283
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6358 - loss: 0.2234 - val_accuracy: 0.6286 - val_loss: 0.2262
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6412 - loss: 0.2215 - val_accuracy: 0.6307 - val_loss: 0.2244
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6435 - loss: 0.2198 - val_accuracy: 0.6394 - val_loss: 0.2228
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6478 - loss: 0.2184 - val_accuracy: 0.6421 - val_loss: 0.2214
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6515 - loss: 0.2171 - val_accuracy: 0.6444 - val_loss: 0.2202
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6568 - loss: 0.2160 - val_accuracy: 0.6474 - val_loss: 0.2192
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6605 - loss: 0.2151 - val_accuracy: 0.6468 - val_loss: 0.2182
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6608 - loss: 0.2142 - val_accuracy: 0.6488 - val_loss: 0.2175
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6630 - loss: 0.2135 - val_accuracy: 0.6485 - val_loss: 0.2168
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6637 - loss: 0.2129 - val_accuracy: 0.6514 - val_loss: 0.2162
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6656 - loss: 0.2123 - val_accuracy: 0.6541 - val_loss: 0.2157
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6667 - loss: 0.2118 - val_accuracy: 0.6535 - val_loss: 0.2152
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6672 - loss: 0.2113 - val_accuracy: 0.6544 - val_loss: 0.2148
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6676 - loss: 0.2109 - val_accuracy: 0.6570 - val_loss: 0.2145
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6688 - loss: 0.2104 - val_accuracy: 0.6588 - val_loss: 0.2141
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6706 - loss: 0.2100 - val_accuracy: 0.6591 - val_loss: 0.2138
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6717 - loss: 0.2096 - val_accuracy: 0.6599 - val_loss: 0.2134
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6724 - loss: 0.2092 - val_accuracy: 0.6605 - val_loss: 0.2131
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6733 - loss: 0.2088 - val_accuracy: 0.6620 - val_loss: 0.2127
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6742 - loss: 0.2084 - val_accuracy: 0.6623 - val_loss: 0.2123
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6750 - loss: 0.2080 - val_accuracy: 0.6623 - val_loss: 0.2119
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6757 - loss: 0.2077 - val_accuracy: 0.6652 - val_loss: 0.2116
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.6768 - loss: 0.2073 - val_accuracy: 0.6649 - val_loss: 0.2112
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6764 - loss: 0.2070 - val_accuracy: 0.6655 - val_loss: 0.2108
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6774 - loss: 0.2066 - val_accuracy: 0.6655 - val_loss: 0.2104
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6777 - loss: 0.2063 - val_accuracy: 0.6667 - val_loss: 0.2101
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6780 - loss: 0.2060 - val_accuracy: 0.6670 - val_loss: 0.2097
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6782 - loss: 0.2057 - val_accuracy: 0.6696 - val_loss: 0.2094
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6778 - loss: 0.2055 - val_accuracy: 0.6713 - val_loss: 0.2091
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6789 - loss: 0.2052 - val_accuracy: 0.6746 - val_loss: 0.2089
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6790 - loss: 0.2050 - val_accuracy: 0.6763 - val_loss: 0.2086
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6796 - loss: 0.2047 - val_accuracy: 0.6763 - val_loss: 0.2084
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6797 - loss: 0.2045 - val_accuracy: 0.6775 - val_loss: 0.2083
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6804 - loss: 0.2043 - val_accuracy: 0.6763 - val_loss: 0.2081
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6807 - loss: 0.2041 - val_accuracy: 0.6757 - val_loss: 0.2080
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6818 - loss: 0.2039 - val_accuracy: 0.6760 - val_loss: 0.2079
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6815 - loss: 0.2038 - val_accuracy: 0.6763 - val_loss: 0.2078
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.6826 - loss: 0.2036 - val_accuracy: 0.6757 - val_loss: 0.2077
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6819 - loss: 0.2034 - val_accuracy: 0.6746 - val_loss: 0.2076
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6829 - loss: 0.2032 - val_accuracy: 0.6746 - val_loss: 0.2075
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6837 - loss: 0.2031 - val_accuracy: 0.6731 - val_loss: 0.2075
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6844 - loss: 0.2029 - val_accuracy: 0.6737 - val_loss: 0.2074
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6840 - loss: 0.2028 - val_accuracy: 0.6740 - val_loss: 0.2074
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6845 - loss: 0.2027 - val_accuracy: 0.6740 - val_loss: 0.2074
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6856 - loss: 0.2025 - val_accuracy: 0.6731 - val_loss: 0.2073
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6862 - loss: 0.2024 - val_accuracy: 0.6728 - val_loss: 0.2073
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6864 - loss: 0.2023 - val_accuracy: 0.6728 - val_loss: 0.2072
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6867 - loss: 0.2022 - val_accuracy: 0.6728 - val_loss: 0.2072
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6865 - loss: 0.2021 - val_accuracy: 0.6734 - val_loss: 0.2071
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6871 - loss: 0.2020 - val_accuracy: 0.6734 - val_loss: 0.2071
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6871 - loss: 0.2019 - val_accuracy: 0.6731 - val_loss: 0.2070
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6872 - loss: 0.2019 - val_accuracy: 0.6722 - val_loss: 0.2070
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6873 - loss: 0.2018 - val_accuracy: 0.6722 - val_loss: 0.2069
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6878 - loss: 0.2017 - val_accuracy: 0.6731 - val_loss: 0.2068
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6880 - loss: 0.2016 - val_accuracy: 0.6725 - val_loss: 0.2068
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6881 - loss: 0.2016 - val_accuracy: 0.6734 - val_loss: 0.2068
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6879 - loss: 0.2015 - val_accuracy: 0.6731 - val_loss: 0.2067
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6880 - loss: 0.2014 - val_accuracy: 0.6731 - val_loss: 0.2067
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6878 - loss: 0.2014 - val_accuracy: 0.6719 - val_loss: 0.2067
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6882 - loss: 0.2013 - val_accuracy: 0.6716 - val_loss: 0.2067
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6884 - loss: 0.2012 - val_accuracy: 0.6725 - val_loss: 0.2066
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6889 - loss: 0.2012 - val_accuracy: 0.6734 - val_loss: 0.2066
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6894 - loss: 0.2011 - val_accuracy: 0.6737 - val_loss: 0.2066
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6897 - loss: 0.2011 - val_accuracy: 0.6743 - val_loss: 0.2066
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.6898 - loss: 0.2010 - val_accuracy: 0.6740 - val_loss: 0.2065
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6890 - loss: 0.2009 - val_accuracy: 0.6737 - val_loss: 0.2065
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6893 - loss: 0.2009 - val_accuracy: 0.6734 - val_loss: 0.2065
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6895 - loss: 0.2008 - val_accuracy: 0.6737 - val_loss: 0.2064
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6892 - loss: 0.2008 - val_accuracy: 0.6728 - val_loss: 0.2064
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6887 - loss: 0.2007 - val_accuracy: 0.6731 - val_loss: 0.2063
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6892 - loss: 0.2006 - val_accuracy: 0.6734 - val_loss: 0.2062
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6893 - loss: 0.2006 - val_accuracy: 0.6743 - val_loss: 0.2062
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6897 - loss: 0.2005 - val_accuracy: 0.6740 - val_loss: 0.2061
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6892 - loss: 0.2005 - val_accuracy: 0.6731 - val_loss: 0.2061
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.6889 - loss: 0.2004 - val_accuracy: 0.6725 - val_loss: 0.2060
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6895 - loss: 0.2004 - val_accuracy: 0.6716 - val_loss: 0.2060
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6894 - loss: 0.2003 - val_accuracy: 0.6725 - val_loss: 0.2059
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6894 - loss: 0.2003 - val_accuracy: 0.6722 - val_loss: 0.2059
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6896 - loss: 0.2002 - val_accuracy: 0.6722 - val_loss: 0.2059
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6896 - loss: 0.2001 - val_accuracy: 0.6722 - val_loss: 0.2058
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6897 - loss: 0.2001 - val_accuracy: 0.6722 - val_loss: 0.2058
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6903 - loss: 0.2000 - val_accuracy: 0.6713 - val_loss: 0.2057
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6903 - loss: 0.2000 - val_accuracy: 0.6711 - val_loss: 0.2057
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6905 - loss: 0.1999 - val_accuracy: 0.6711 - val_loss: 0.2056
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6908 - loss: 0.1998 - val_accuracy: 0.6716 - val_loss: 0.2056
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6907 - loss: 0.1998 - val_accuracy: 0.6725 - val_loss: 0.2055
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6908 - loss: 0.1997 - val_accuracy: 0.6728 - val_loss: 0.2055
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6904 - loss: 0.1997 - val_accuracy: 0.6725 - val_loss: 0.2054
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6725 - loss: 0.2054
0.20542724430561066 0.6725197434425354

By Pytorch

In [85]:
import torch.nn
import torch
import torch.nn as nn

to_t = lambda a: torch.tensor(a, dtype=torch.float32)
x_train, x_val, x_test = to_t(x_train), to_t(x_val), to_t(x_test)
y_train, y_val, y_test = to_t(y_train), to_t(y_val), to_t(y_test)
print(x_train.shape) 
print(y_train.shape)



class VillainNet (nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(26,8)
        self.output = nn.Linear(8,1)

    def forward(self,x):
        x = torch.relu(self.hidden(x))
        x = torch.sigmoid(self.output(x))
        return x

torch.manual_seed(42)
model = VillainNet()
print(model)

loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.01)

print(loss_fn)
print(optimizer)

torch.Size([13666, 26])
torch.Size([13666, 1])
VillainNet(
  (hidden): Linear(in_features=26, out_features=8, bias=True)
  (output): Linear(in_features=8, out_features=1, bias=True)
)
MSELoss()
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)

/tmp/ipykernel_49/2509212718.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  to_t = lambda a: torch.tensor(a, dtype=torch.float32)

In [86]:
num_epochs = 100

for epoch in range(num_epochs):
    predictions = model(x_train)
    loss = loss_fn(predictions, y_train)

    optimizer.zero_grad()
    loss.backward() 
    optimizer.step()

In [88]:
model.eval()
with torch.no_grad():
    probs = model(x_test)
    predicted_classes = (probs > 0.5).float()
    accuracy = (predicted_classes == y_test).float().mean()
    print(f'Test accuracy: {accuracy:.3f}') 
    
from sklearn.metrics import classification_report
print(classification_report(y_test.numpy(), predicted_classes.numpy()))

Test accuracy: 0.673
              precision    recall  f1-score   support

         0.0       0.68      0.54      0.60      1565
         1.0       0.67      0.79      0.72      1852

    accuracy                           0.67      3417
   macro avg       0.67      0.66      0.66      3417
weighted avg       0.67      0.67      0.67      3417